# Generated by Django 5.2 on 2025-06-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=128)),
                ('size', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('dimensions', models.CharField(blank=True, default='', max_length=16)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=32)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('p', 'در انتظار'), ('s', 'ارسال شده')], default='p', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bin')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
    ]
