# Generated by Django 5.2 on 2025-07-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('brand', models.CharField(max_length=128, verbose_name='برند')),
                ('size', models.PositiveIntegerField(verbose_name='سایز')),
                ('color', models.CharField(max_length=32, verbose_name='رنگ')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('dimensions', models.CharField(blank=True, default='', max_length=16, verbose_name='ابعاد')),
                ('image', models.ImageField(upload_to='products/', verbose_name='عکس')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سطل',
                'verbose_name_plural': 'سطل',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=32, verbose_name='کد پستی')),
                ('lng', models.FloatField(verbose_name='طول جغرافیایی')),
                ('lat', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('p', 'در انتظار'), ('s', 'ارسال شده')], default='p', max_length=1, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='PostagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.PositiveIntegerField(verbose_name='قیمت اولیه')),
                ('per_km', models.PositiveIntegerField(verbose_name='قیمت به ازای هر کیلومتر')),
            ],
            options={
                'verbose_name': 'هزینه پست',
                'verbose_name_plural': 'هزینه پست',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bin', verbose_name='سطل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='سفارش')),
            ],
        ),
    ]
