# Generated by Django 5.2 on 2025-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postageprice',
            name='up_to_size',
            field=models.PositiveIntegerField(default=0, verbose_name='تا حجم'),
            preserve_default=False,
        ),
    ]
