# Generated by Django 5.2 on 2025-06-18 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'verbose_name': 'سطل', 'verbose_name_plural': 'سطل'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterField(
            model_name='bin',
            name='brand',
            field=models.CharField(max_length=128, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='color',
            field=models.CharField(max_length=32, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='ابعاد'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='size',
            field=models.PositiveIntegerField(verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='title',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=32, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=32, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'در انتظار'), ('s', 'ارسال شده')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bin', verbose_name='سطل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
    ]
